export const queryKeys = {
  moodFeed: (scope: string, params?: unknown) => ["moods", "feed", scope, params] as const,
  moodDetail: (moodId: string) => ["moods", "detail", moodId] as const,
  moodSearch: (params: unknown) => ["moods", "search", params] as const,
  moodComments: (moodId: string) => ["comments", moodId] as const,
  reactions: (targetType: string, targetId: string) => ["reactions", targetType, targetId] as const,
  bookmarks: (params?: unknown) => ["bookmarks", params] as const,
  bookmarkStatus: (moodId: string) => ["bookmarks", "status", moodId] as const,
  statisticsDashboard: (params: unknown) => ["statistics", "dashboard", params] as const,
  trending: (params: unknown) => ["statistics", "trending", params] as const,
  emotionTags: ["tags", "emotions"] as const,
  imageUrl: (imageId: string) => ["images", "url", imageId] as const,
  adminDashboard: ["admin", "dashboard"] as const,
  adminReports: (params?: unknown) =>
    params === undefined ? (["admin", "reports"] as const) : (["admin", "reports", params] as const),
  adminUsers: (params?: unknown) =>
    params === undefined ? (["admin", "users"] as const) : (["admin", "users", params] as const),
  adminAuditLogs: (params?: unknown) => ["admin", "audit-logs", params] as const,
  adminContentMoods: (params?: unknown) => ["admin", "content-moods", params] as const,
  adminFaculties: ["admin", "faculties"] as const,
  adminMajors: ["admin", "majors"] as const,
  adminMoodTags: ["admin", "mood-tags"] as const,
  adminPendingSubmissions: (params?: unknown) => ["admin", "pending-submissions", params] as const,
  notifications: (params?: unknown) => ["notifications", params] as const,
};
