export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  authCallback: "/auth/callback",
  settings: "/settings",
  howToUse: "/how-to-use",
  feed: "/feed",
  create: "/create",
  bookmarks: "/bookmarks",
  search: "/search",
  statistics: "/statistics",
  trending: "/trending",
  notifications: "/notifications",
  admin: "/admin",
  adminReports: "/admin/reports",
  adminUsers: "/admin/users",
  adminAudit: "/admin/audit-logs",
  moodDetail: (moodId: string) => `/mood/${moodId}`,
  facultyFeed: (facultyId: string) => `/faculty/${facultyId}`,
  majorFeed: (majorId: string) => `/major/${majorId}`,
} as const;
