export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  authCallback: "/auth/callback",
  settings: "/settings",
  howToUse: "/how-to-use",
  feed: "/feed",
  create: "/create",
  bookmarks: "/bookmarks",
  groups: "/groups",
  groupDetail: (groupId: string) => `/groups/${groupId}`,
  search: "/search",
  dashboard: "/dashboard",
  statistics: "/statistics",
  trending: "/trending",
  notifications: "/notifications",
  admin: "/admin",
  adminReports: "/admin/reports",
  adminUsers: "/admin/users",
  adminAudit: "/admin/audit-logs",
  adminPosts: "/admin/posts",
  adminFaculties: "/admin/faculties",
  adminMajors: "/admin/majors",
  adminMoods: "/admin/moods",
  adminPending: "/admin/pending",
  moodDetail: (moodId: string) => `/mood/${moodId}`,
  facultyFeed: (facultyId: string) => `/faculty/${facultyId}`,
  majorFeed: (majorId: string) => `/major/${majorId}`,
} as const;
